[script.radioparadise] 1.0.0
xbmc/repo-scripts pull request #1832
Opened 2021-01-31 12:06 UTC by 7adietri

### Description
Plays [Radio Paradise](https://radioparadise.com/) music mixes along with the HD slideshow in the Kodi music player.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

2021-02-11 21:48 UTC, enen92 commented on script.radioparadise/resources/skins/Default/720p/radioparadise.xml
> +<?xml version="1.0" encoding="UTF-8"?>
please rename to script-radioparadise.xml (we use this as a naming convention to avoid confusion with skin xml files)

2021-02-11 21:48 UTC, enen92 commented on script.radioparadise/script.py
> +        xbmc.executebuiltin('Container.SetViewMode(50)')
Please use another range of viewmodes as 50 is used by estuary

2021-02-11 21:50 UTC, enen92 commented on script.radioparadise/script.py
> +        window = Window('radioparadise.xml', addon_path)
see comment above

2021-02-11 21:51 UTC, enen92 requested changes
Thanks for the submission.
See comments. Sorry for the time taken for checking your addon.

2021-02-11 23:58 UTC, 7adietri commented
@enen92 Fixed, thanks for the review!

2021-02-12 00:33 UTC, enen92 approved these changes

2021-02-12 00:33 UTC, merged