[script.module.youtube.dl] 21.204.0+matrix.1
xbmc/repo-scripts pull request #1836
Opened 2021-02-04 08:44 UTC by sy6sy2

### Description

This is simply a portage of Youtube-DL on Matrix repo.
The code is exactly the same as the one in Leia branch except:

* Usage of `xbmc.LOGINFO` because of Matrix changes
* Update YT-dl core to 2021.02.04.1 version

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

2021-02-06 22:26 UTC, Lunatixz commented
@sy6sy2 did discuss changes with @ruuk ?

2021-02-07 08:09 UTC, sy6sy2 commented
Hi asked him multiple times on Slack without any success 😕. 
I did not modify anything in the script except the minimal changes to work on Matrix and an update of YT-DL on upstream. 
Matrix release will come soon and this script is still not available on Matrix repo 😕Some plugins and scripts use YT-DL script as dependency, this is why I asked @enen92 about this submission. 
There is some PR (fix and new features) open still a long time on ruuk GitHub but ruuk seems to be busy, also on Leia repo, YT-DL needs an update to upstream.

2021-02-08 06:56 UTC, ruuk commented
> asked him multiple times on Slack without any success

While you did message me a few times asking when I was going to update the add-on for Matrix, you didn't mention you were going to do your own submission :)

If your interested in taking over maintenance of the add-on I'd be fine with that. Otherwise, it would probably be best to PR your changes to the branch in my repo. I haven't had time to work on Matrix compatibility, but I can fit in a PR review and submission.

2021-02-08 07:43 UTC, sy6sy2 commented
> While you did message me a few times asking when I was going to update the add-on for Matrix, you didn't mention you were going to do your own submission :)

Hi @ruu., Yes you are right, my last message on Slack about YT-DL is from 24/01 and because you did not answer me I assumed you were busy with other things, that's why I didn't send you any more messages about that in order to not spam you or annoy you about that. But I don't want to offense you or take your "place", just want to help 😉 

I'm agree to take maintenance of the YT-DL script, if it's Ok for you?

2021-02-08 17:37 UTC, ruuk commented
That's fine with me, and I would appreciate it. I'm not using Kodi anymore, so I don't have a personal interest in the add-on at this point. It would be better to have someone maintaining it who actually uses it.

2021-02-08 19:35 UTC, Lunatixz commented
@ruuk it's okay to accept all future YT-DL submissions from @sy6sy2 ?

2021-02-08 22:39 UTC, ruuk commented
Yes, thanks.

2021-02-09 01:10 UTC, Lunatixz commented
Great thanks!! ping @enen92

2021-02-09 08:30 UTC, enen92 commented
> Great thanks!! ping @enen92 

Yes?

2021-02-11 18:35 UTC, Lunatixz requested changes

2021-02-11 18:35 UTC, Lunatixz commented on script.module.youtube.dl/service.py
> +                xbmc.sleep(100)
Please changed to ` if xbmc.waitForAbort(0.1): break`

2021-02-11 18:35 UTC, Lunatixz commented on script.module.youtube.dl/lib/YDStreamUtils.py
> +            new = xbmcgui.Dialog().yesno(T(32005), T(32006), path, T(32007), T(32008), T(32009))
All Matrix dialogs have changed, no longer supports additional lines.
 https://codedocs.xyz/xbmc/xbmc/group__python___dialog.html#ga4541bc893b3ef70391cb299d6f522ccf

2021-02-11 19:07 UTC, enen92 commented on script.module.youtube.dl/.gitattributes
> +.gitignore export-ignore
please remove from the submisson

2021-02-11 19:08 UTC, enen92 commented on script.module.youtube.dl/lib/yd_private_libs/servicecontrol.py
> +        addonPath = xbmc.translatePath(util.ADDON.getAddonInfo('path')).decode('utf-8')
xbmcvfs

2021-02-12 16:28 UTC, sy6sy2 commented
Done 😉

2021-02-14 18:54 UTC, enen92 commented on script.module.youtube.dl/service.py
> +sys.path.insert(0, util.MODULE_PATH)
no sys.path changes, please refactor the implementation

2021-02-14 18:54 UTC, enen92 requested changes
Sorry for yet another request

2021-02-24 10:10 UTC, sy6sy2 commented
Sorry for the delay @enen92, changes applied.

2021-02-24 18:58 UTC, enen92 commented on script.module.youtube.dl/addon.xml
> +<addon id="script.module.youtube.dl" name="youtube-dl Control" version="21.204.0+matrix.1" provider-name="sy6sy2 based on ruuk's work">
authors need to be separated by commas. Since this module is a patched version of youtube_dl, please use:
originalauthor, ruuk, you

2021-02-24 18:58 UTC, enen92 commented on script.module.youtube.dl/addon.xml
> +        <source>https://github.com/ruuk/script.module.youtube.dl</source>
as the new mantainer please define your new upstream

2021-02-24 19:20 UTC, sy6sy2 commented
Done 😉

2021-02-24 19:26 UTC, enen92 approved these changes

2021-02-24 19:26 UTC, merged

2021-02-24 19:26 UTC, enen92 commented
Sorry for so many requests :)

2021-02-24 19:59 UTC, sy6sy2 commented
No problem! Thank you for your time.
I will try to backport main changes to Leia repo so that Leia and Matrix version will be the "same" in the future expect for the specific matrix things.