[script.adzapper] 1.0.1
xbmc/repo-scripts pull request #1856
Opened 2021-02-20 19:06 UTC by popy2k14

### Description
Update for matrix
### Checklist:

- [ ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X ] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

2021-02-20 19:27 UTC, popy2k14 commented
Could not find out what's going wrong with Travis build. Any hints?

2021-02-20 20:21 UTC, pkscout commented
Good news and bad news. The good news is I triggered another run of the Travis checks and it worked. The bad news is you have some stuff to work through (see the Travis details for the logs and issues).

2021-02-21 11:53 UTC, popy2k14 commented
Fixed the screenshot already locally and can commit it.
Sadly i dont know what the whole XML schema is about.

Can you please help me fixing it?

Thx

2021-02-21 12:22 UTC, enen92 commented on script.adzapper/addon.xml
> +		<license>GNU GENERAL PUBLIC LICENSE. Version 2, June 1991</license>
GPL-2.0-only or GPL-2.0-or-later

2021-02-21 12:23 UTC, enen92 commented on script.adzapper/addon.xml
> +		<disclaimer lang="en_GB"></disclaimer>
If disclaimer is set you need to provide some text, otherwise just remove from addon.xml

2021-02-21 12:23 UTC, enen92 commented on script.adzapper/addon.xml
> +	<extension point="xbmc.service" library="service.py" start="login"/>
Drop the start argument

2021-02-21 12:23 UTC, enen92 commented on script.adzapper/addon.xml
> +		<email></email>
Please drop if empty

2021-02-21 12:24 UTC, enen92 commented on script.adzapper/addon.xml
> +		<news></news>
Please drop if empty or provide text/content

2021-02-21 14:38 UTC, popy2k14 commented
thx. corrected all and force pushed new PR

2021-02-21 15:35 UTC, enen92 commented on script.adzapper/resources/lib/settings.py
> +# -*- coding: utf-8 -*-
Please remove all the .pyc files from the submission. Add __pycache__ to gitignore

2021-02-21 15:36 UTC, enen92 requested changes
After the drop of compiled files it's good to go

2021-02-21 15:54 UTC, popy2k14 commented
Sorry, have copied it from my test kodi installation.
Should now be clean :-)

2021-02-21 16:16 UTC, enen92 approved these changes
All good

2021-02-21 16:16 UTC, merged

2021-02-21 16:19 UTC, popy2k14 commented
thx for merging