[script.video.randomtv] 1.3.0
xbmc/repo-scripts pull request #1870
Opened 2021-02-23 23:48 UTC by gmccauley

### Description
v1.3.0 (23 February 2021)
  - Added support for Matrix / python 3

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

2021-02-23 23:58 UTC, enen92 commented on script.video.randomtv/addon.xml
> +    <language></language>
Please drop

2021-02-23 23:58 UTC, enen92 commented on script.video.randomtv/addon.xml
> +    <license>GNU General Public License, v2</license>
GPL-2.0-only or GPL-2.0-or-later (spdx identifiers)

2021-02-24 00:00 UTC, enen92 commented on script.video.randomtv/addon.xml
> +v1.3.0 (23 February 2021)
Please use news for the most recent changes. You can ship a changelog.txt with the whole changelog
T

2021-02-24 00:01 UTC, enen92 requested changes
Minors. Thanks for the update.

2021-02-24 01:19 UTC, gmccauley commented
> Minors. Thanks for the update.

Thanks.  I've updated, but I don't know git well enough to squash them into this commit / pull request.  So I'll close this one and open another.

2021-02-24 01:19 UTC, closed without merging