[script.video.bgtime_tv] 1.0.8 Initial matrix support
xbmc/repo-scripts pull request #1874
Opened 2021-02-26 11:38 UTC by portokala123

### Description
Video plugin for bgtime.tv service. Addes support for matrix

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

2021-02-26 21:39 UTC, enen92 commented
ERROR: Image icon should be explicitly declared in addon.xml <assets>.

2021-02-26 21:39 UTC, enen92 commented on script.video.bgtime_tv/addon.xml
> +		<license>The MIT License (MIT)</license>
please use only "MIT"

2021-02-26 21:40 UTC, enen92 commented on script.video.bgtime_tv/const.py
> +PROFILE_PATH    = xbmc.translatePath( ADDON.getAddonInfo('profile') )
xbmcvfs.translatePath

2021-02-26 21:40 UTC, enen92 commented on script.video.bgtime_tv/const.py
> +ADDONPATH       = xbmc.translatePath( ADDON.getAddonInfo('path') )
xbmcvfs.translatePath

2021-02-26 21:40 UTC, enen92 commented on script.video.bgtime_tv/gui.py
> +			xbmcgui.Dialog().ok('Missing inputstream.adaptive add-on', 'inputstream.adaptive add-on not found or not enabled.This add-on is required to view DRM protected content.')
this needs to be localized as it is shown in the ui

2021-02-26 21:42 UTC, enen92 commented on script.video.bgtime_tv/gui.py
> +				ans = dialog.yesno(const.LANG(32003), 'За да използвате услугата трябва да се впишете')
localize

2021-02-26 21:43 UTC, enen92 commented on script.video.bgtime_tv/gui.py
> +	def writeInFile(self):
with open(const.TOKEN_FILEPATH, "w+") as fopen:
    f.write()

2021-02-26 21:43 UTC, enen92 commented on script.video.bgtime_tv/gui.py
> +			fopen = open(const.TOKEN_FILEPATH, "r")
same

2021-02-26 21:46 UTC, enen92 requested changes
see comments

2021-03-01 08:53 UTC, portokala123 commented
All problems fixed. I also found some bugs in navigaition, so i fixed them also.

2021-03-01 09:10 UTC, enen92 approved these changes

2021-03-01 09:11 UTC, enen92 commented
Please check Travis failure:
ERROR: Image icon should be explicitly declared in addon.xml <assets>.

2021-03-01 09:12 UTC, enen92 commented
Info: https://kodi.wiki/view/Addon.xml#.3Cassets.3E

2021-03-14 16:44 UTC, enen92 approved these changes

2021-03-14 16:45 UTC, merged