[script.commands] 1.1.0
xbmc/repo-scripts pull request #1899
Opened 2021-03-03 23:23 UTC by RomanSmolka

### Description
This is a Matrix port of the [Commands addon](https://kodi.wiki/view/Add-on:Commands) originally made by @AddonScriptorDE. The author has been inactive on both GitHub and Kodi forum since 2015.

- No functional changes have been made. 
- Language files were recreated to use the .po format
- default.py script was updated for Python 3.

### Checklist:

- [x ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x ] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

2021-03-03 23:34 UTC, enen92 requested changes
See comments

2021-03-03 23:34 UTC, enen92 commented on script.commands/README.md
> +Map multiple XBMC commands to one remote button. All availabe commands: https://kodi.wiki/view/List_of_built-in_functions
```suggestion
Map multiple Kodi commands to one remote button. All available commands: https://kodi.wiki/view/List_of_built-in_functions
```

2021-03-03 23:34 UTC, enen92 commented on script.commands/README.md
> +This is a fork of the apparently abandoned addon made by AddonScriptorDE. It has been updated to work with Kodi 19 Matrix.
```suggestion
This is a fork of the abandoned commands XBMC addon made by AddonScriptorDE. It has been updated to work with Kodi 19 Matrix.
```

2021-03-03 23:34 UTC, enen92 commented on script.commands/addon.xml
> +      <summary lang="en">Map multiple XBMC commands to one remote button. All availabe commands: https://kodi.wiki/view/List_of_built-in_functions</summary>
```suggestion
      <summary lang="en_GB">Map multiple XBMC commands to one remote button. All availabe commands: https://kodi.wiki/view/List_of_built-in_functions</summary>
```

2021-03-03 23:34 UTC, enen92 commented on script.commands/addon.xml
> +      <summary lang="de">Mehrere XBMC Befehle einer Taste zuweisen. Alle verfügbaren Befehle: https://kodi.wiki/view/List_of_built-in_functions</summary>
```suggestion
      <summary lang="de_DE">Mehrere XBMC Befehle einer Taste zuweisen. Alle verfügbaren Befehle: https://kodi.wiki/view/List_of_built-in_functions</summary>
```

2021-03-03 23:34 UTC, enen92 commented on script.commands/addon.xml
> +      <language></language>
Remove, this only applies to media content

2021-03-03 23:34 UTC, enen92 commented on script.commands/addon.xml
> +      <source>https://github.com/AddonScriptorDE/script.commands</source>
This needs to be the new upstream location of the code

2021-03-03 23:34 UTC, enen92 commented on script.commands/addon.xml
> +      <website></website>
drop if empty

2021-03-03 23:34 UTC, enen92 commented on script.commands/addon.xml
> +      <license>GNU GENERAL PUBLIC LICENSE. Version 2, June 1991</license>
```suggestion
      <license>GPL-2.0-only</license>
```

2021-03-03 23:34 UTC, enen92 commented on script.commands/changelog.txt
> +1.0.0
Changelog is missing your new version. Also, Kodi now has the `<news>` element in addon xml to display the news regarding the latest addon version. Consider to use it.

2021-03-03 23:34 UTC, enen92 commented on script.commands/commands.list
> +SimplePlaylists: Add###RunPlugin(plugin://script.simpleplaylists/?mode=addCurrentUrl)
I'm not aware of this addon in our repo, please drop the action

2021-03-03 23:34 UTC, enen92 commented on script.commands/commands.list
> +SimplePlaylists: View###RunPlugin(plugin://script.simpleplaylists/?mode=showPlaylists)
same

2021-03-03 23:34 UTC, enen92 commented on script.commands/commands.list
> +Play DVD###PlayDVD
Deprecated, use PlayDisc

2021-03-03 23:34 UTC, enen92 commented on script.commands/commands.list
> +Restart XBMC###RestartApp
Kodi

2021-03-03 23:34 UTC, enen92 commented on script.commands/commands.list
> +Quit XBMC###Quit
Kodi

2021-03-03 23:34 UTC, enen92 commented on script.commands/default.py
> +addon_work_folder=xbmc.translatePath("special://profile/addon_data/"+addonID)
```suggestion
addon_work_folder=xbmcvfs.translatePath("special://profile/addon_data/"+addonID)
```

2021-03-03 23:34 UTC, enen92 commented on script.commands/default.py
> +commandsFile=xbmc.translatePath('special://profile/addon_data/'+addonID+'/commands')
```suggestion
commandsFile=xbmcvfs.translatePath('special://profile/addon_data/'+addonID+'/commands')
```

2021-03-03 23:34 UTC, enen92 commented on script.commands/default.py
> +import xbmc, xbmcgui, xbmcaddon, locale, sys, re, os
```suggestion
import xbmc, xbmcgui, xbmcaddon, xbmcvfs, locale, sys, re, os
```

2021-03-03 23:34 UTC, enen92 commented on script.commands/default.py
> +commandsList=xbmc.translatePath('special://home/addons/'+addonID+'/commands.list')
```suggestion
commandsList=xbmcvfs.translatePath('special://home/addons/'+addonID+'/commands.list')
```

2021-03-03 23:34 UTC, enen92 commented on script.commands/default.py
> +favsFile=xbmc.translatePath("special://profile/favourites.xml")
```suggestion
favsFile=xbmcvfs.translatePath("special://profile/favourites.xml")
```

2021-03-03 23:34 UTC, enen92 commented on script.commands/default.py
> +            fh = open(commandsFile+key, 'a')
```python
with open(commandsFile+key, 'a') as fh:
    fh.write(title+"###"+currentCombo+"\n")
```

2021-03-03 23:34 UTC, enen92 commented on script.commands/default.py
> +          fh = open(commandsList, 'r')
same, use python's `with`

2021-03-03 23:34 UTC, enen92 commented on script.commands/default.py
> +              fh = open(commandsFile+key, 'a')
same

2021-03-03 23:34 UTC, enen92 commented on script.commands/default.py
> +          for line in fh:
same

2021-03-03 23:34 UTC, enen92 commented on script.commands/default.py
> +              fh = open(commandsFile+key, 'a')
same

2021-03-03 23:34 UTC, enen92 commented on script.commands/default.py
> +                fh=open(commandsFile+key, 'w')
same

2021-03-03 23:34 UTC, enen92 commented on script.commands/default.py
> +                fh = open(commandsFile+key, 'r')
same

2021-03-03 23:34 UTC, enen92 commented on script.commands/default.py
> +            fh = open(commandsFile+key, 'r')
same

2021-03-03 23:34 UTC, enen92 commented on script.commands/default.py
> +            fh.close()
same

2021-03-03 23:34 UTC, enen92 commented on script.commands/default.py
> +              fh = open(commandsFile+key, 'r')
same

2021-03-03 23:34 UTC, enen92 commented on script.commands/default.py
> +              fh.close()
same

2021-03-03 23:34 UTC, enen92 commented on script.commands/default.py
> +              fh=open(commandsFile+key, 'w')
same

2021-03-03 23:34 UTC, enen92 commented on script.commands/addon.xml
> +  </extension>
icon has to be specified in addon.xml (`assets`)

2021-03-04 00:52 UTC, RomanSmolka commented
Thank you for the fast response, much appreciated! PR has been updated with all your suggested changes.

2021-03-04 09:38 UTC, enen92 approved these changes
You still have a lot of places where you open and close the filehandlers. Please consider updating the code in the future to use `with` whenever possible (that will ensure the handler is always closed).

2021-03-04 09:39 UTC, enen92 commented
Please check travis failures, you have a few files marked as executable:
https://travis-ci.com/github/xbmc/repo-scripts/builds/218919200

2021-03-04 13:52 UTC, RomanSmolka commented
Fixed, looks ok now.

2021-03-04 14:30 UTC, enen92 commented
Yeah, sure. Not everything is bad with a complete "new beginning" we enforced in matrix, at least there's the chance to cleanup and improve on the old base :)

2021-03-04 14:30 UTC, merged