[script.simkl] 3.0.0
xbmc/repo-scripts pull request #1923
Opened 2021-03-16 18:57 UTC by ekleop

### Description
Added support for Kodi 19, same functionality as previous version in Jarvis push.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

2021-03-19 23:08 UTC, enen92 requested changes
See comments

2021-03-19 23:08 UTC, enen92 commented on script.simkl/addon.xml
> +    <summary lang="en">Simkl Scrobbler with AI file detection system</summary>
```suggestion
    <summary lang="en_GB">Simkl Scrobbler with AI file detection system</summary>
```

2021-03-19 23:08 UTC, enen92 commented on script.simkl/addon.xml
> +  <extension point="xbmc.service" library="service.py" start="login" />
```suggestion
  <extension point="xbmc.service" library="service.py" />
```

2021-03-19 23:08 UTC, enen92 commented on script.simkl/addon.xml
> +    <description lang="en">Automatically set Movies and TV Shows\Anime as watched on Simkl.com. Simkl knows what you're watching, tells you episodes you've missed, and connects you to what your frien
```suggestion
    <description lang="en_GB">Automatically set Movies and TV Shows\Anime as watched on Simkl.com. Simkl knows what you're watching, tells you episodes you've missed, and connects you to what your friends are into. Sign up at https://simkl.com to get all of these features: &#10;&#10;- Automatically track what you’re watching.&#10;- Receive notifications about new episodes.&#10;- Find recommendations based on your watch history.&#10;- See your friend's ratings.&#10;&#10;Simkl was created to help people, like you, to keep track of what you watch and receive notifications about new episodes and new movie releases based on your preferences and watch history.</description>
```

2021-03-19 23:08 UTC, enen92 commented on script.simkl/addon.xml
> +    <license>GPLv3</license>
```suggestion
    <license>GPL-3.0-only</license>
```

or

```suggestion
    <license>GPL-3.0-or-later</license>
```

2021-03-19 23:08 UTC, enen92 commented on script.simkl/service.py
> +    log("dir = " + str(xbmc.translatePath("special://home")))
```suggestion
    log("dir = " + str(xbmcvfs.translatePath("special://home")))
```

2021-03-20 11:39 UTC, ekleop commented
Everything was updated according your guide, thanks

2021-03-20 13:16 UTC, enen92 approved these changes

2021-03-20 13:17 UTC, merged