[weather.metoffice] 2.0.2
xbmc/repo-scripts pull request #1965
Opened 2021-04-04 14:08 UTC by powlo

### Description
Updates weather.metoffice for leia with minor fixes.
### Checklist:
- [X ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [ X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

2021-04-10 21:30 UTC, enen92 requested changes

2021-04-10 21:30 UTC, enen92 commented on weather.metoffice/addon.xml
> +    <license>GNU GPL v2</license>
GPL-2.0-only or GPL-2.0-or-later

2021-04-10 21:30 UTC, enen92 commented on weather.metoffice/addon.xml
> +    <email></email>
Drop if empty

2021-04-10 21:30 UTC, enen92 commented on weather.metoffice/addon.xml
> +    <language>en</language>
Remove language tag, only applies to media (not weather)

2021-04-10 21:30 UTC, enen92 commented on weather.metoffice/addon.xml
> +    <summary lang="en">UK weather forecast from the Met Office.</summary>
en_GB

2021-04-10 21:30 UTC, enen92 commented on weather.metoffice/addon.xml
> +    <description lang="en">UK weather forecast provided by Met Office (http://www.metoffice.gov.uk/)</description>
en_GB

2021-04-10 21:30 UTC, enen92 commented on weather.metoffice/exclude.lst
> +*.pyc
Remove from submissiom

2021-04-10 21:30 UTC, enen92 commented on weather.metoffice/src/metoffice/utilities.py
> +def xbmcbusy(f):
This doesn't work anymore, use dialogbusynocancel

2021-04-12 16:57 UTC, powlo commented
@enen92 thanks for the PR feedback. Do you prefer fixes to be in a rebase (so keeping the "one commit" rule), or a new commit containing the fixes?

2021-04-12 19:03 UTC, enen92 commented
I prefer actually a new commit to avoid having to go over all the code again. We'll squash when merging, thanks

2021-04-18 18:57 UTC, powlo commented
@enen92 see fixes in f3aa61f.

2021-04-18 19:07 UTC, enen92 approved these changes

2021-04-18 19:07 UTC, merged