[script.timers] 2.0.0
xbmc/repo-scripts pull request #2028
Opened 2021-05-28 19:32 UTC by Heckie75

### Description
Powerful timers for KODI

I wanted to have a Kodi addon that is a sleep timer, a doze timer, has several other timer slots and combines it with fading volume in and out over a certain period.

Overview of features:
* 10 timer slots. All of them can be quickly set up by using context menu
* 2 additional slots for sleep and doze timers with single-click-setup 
* Timers can play any ressource that it available in Kodi, e.g. music, video files, TV/radio programs, ressources from 3rd party plugins, e.g. Zattoo channels. 
* Different schedule modes: once, everyday, Mon-Fri, Fri-Sat, Sat-Sun, Sun-Thu, Mon-Thu, specific weekday and many more
* Date change is supported, e.g. from 23:30 (p.m.) until 1:30 (a.m.) 
* Two end modes, i.e. duration or specific time
* Actions related to media: start media and stop at end, just start media, start media at end, stop media immediately, stop media at end, powerdown system
* Linear fading in timer period: fade-in, fade-out, no fading. Min and max volume can be set for each timer
* Custom label for timer
* After KODI startup timers, that are in period, start retroactivly altought KODI was not running at start time. Fading volume is calculated correctly.
* MS Windows only: Feature in order to prevent that Windows displays lock screen if Kodi idles

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

2021-07-15 21:02 UTC, ronie requested changes
please remove the `script.timers/__init__.py` file, as it's not needed.

2021-07-16 06:10 UTC, Heckie75 commented on script.timers/addon.py
> +__PLUGIN_ID__ = "script.timers"
Ok, has been changed

2021-07-16 06:13 UTC, Heckie75 commented on script.timers/addon.xml
> +			<screenshot>resources/assets/screenshot_12.png</screenshot>
Ok, changed as well

2021-07-16 06:15 UTC, Heckie75 commented on script.timers/program.py
> +
Also changed

2021-07-16 06:16 UTC, Heckie75 commented on script.timers/resources/lib/timer/abstract_set_timer.py
> +
Also changed

2021-07-16 06:32 UTC, Heckie75 commented on script.timers/resources/lib/timer/abstract_set_timer.py
> +
I have just pushed the changes. Pls. take another look at it.

Thanks!

2021-07-16 17:26 UTC, ronie approved these changes

2021-07-16 17:36 UTC, ronie commented
thanx for the quick fixes!

looks ok to me now, apart from 1 thing i missed when reviewing the addon.
please add the python dependency to your addon.xml file:
```
	<requires>
		<import addon="xbmc.python" version="3.0.0"/>
	</requires>
```

once that's in place, this pr should be good to go.

2021-07-16 19:12 UTC, Heckie75 commented
I have also added the <requires>. I hope that it is fine. 

Pls. take a look at it.

Thanks for your efforts.

2021-07-17 09:57 UTC, merged

2021-07-17 09:57 UTC, ronie commented
thx!