[script.subtitles.zimukux] 0.1.1
xbmc/repo-scripts pull request #2048
Opened 2021-06-21 05:39 UTC by pizzamx

### Add-on details:

- **General**
  - Add-on name: ZiMuKuX
  - Add-on ID: script.subtitles.zimukux
  - Version number: 0.1.1
  - Kodi/repository version: Matrix
- **Code location**
  - URL: https://github.com/pizzamx/zimuku_for_kodi
  - Revision/tag: v0.1.1
  - Branch: master

### Description of changes:
ZiMuKuX is a subtitle script for Kodi 19+ to download matching subtitle from ZiMuKu ( 字幕库 in Chinese, URL for now is [http://zimuku.org/](http://zimuku.org/)), originally forked from [https://github.com/taxigps/xbmc-addons-chinese/tree/master/service.subtitles.zimuku](https://github.com/taxigps/xbmc-addons-chinese/tree/master/service.subtitles.zimuku). This script is designed for Chinese users but anyone is welcomed to try.

### Checklist:
- [ ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-resources/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

2021-06-30 19:06 UTC, romanvm requested changes
Please check the comments to `addon.xml` and the one about a hardcoded UI string. Other comments are not mandatory.

2021-06-30 19:06 UTC, romanvm commented on script.subtitles.zimukux/resources/lib/sub_provider_service.py
> +def get_params():
The whole function can be replace with `dict(parse_qsl(sys.argv[2][1:]))`

2021-06-30 19:06 UTC, romanvm commented on script.subtitles.zimukux/resources/lib/sub_provider_service.py
> +        if item['episode'].lower().find("s") > -1:
`if 's' in item['episode'].lower()`

2021-06-30 19:06 UTC, romanvm commented on script.subtitles.zimukux/resources/lib/sub_provider_service.py
> +        if (item['file_original_path'].find("http") > -1):
The same: `if 'http' in item['file_original_path']`

2021-07-01 15:04 UTC, pizzamx commented
Please review this commit, which has addressed the issues

2021-07-03 06:38 UTC, romanvm commented
You still haven't fixed a hardcoded UI string in `sub_provider_service.py:106`. Please move the string to translation files.

2021-07-05 18:48 UTC, romanvm approved these changes
LGTM now

2021-07-13 05:26 UTC, pizzamx commented
Anything else I should submit or action I should take? @romanvm

2021-07-13 19:11 UTC, romanvm approved these changes
LGTM

2021-07-15 19:50 UTC, merged