[script.module.kodi65] 1.2.1+matrix.5
xbmc/repo-scripts pull request #2087
Opened 2021-08-16 13:54 UTC by fbacher

### Description
Matrix version of script. The original owner, Philipp Temminghof
(kodi65), is listed as retired and has not responded to several notes.
As far as I can tell his last post was in 2017. scott967 made some
updates for matrix as well as a minor new feature that he required. I
made addon.xml dependency changes and other minor stuff. I am
willing to take over ownership of this addon just so that it doesn't die.

The source is at: https://github.com/fbacher/script.module.kodi65/tree/Matrix-RC1
### Checklist:

- [X ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X ] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

2021-08-17 16:10 UTC, enen92 commented
Hey @fbacher thanks for the submission. Have you seen my comment on the forum thread? Is changing the add-on name and Id an option for you? Usually we only accept Kodi/XBMC branded add-ons if maintained/created by team Kodi.

2021-08-17 16:55 UTC, fbacher commented
Is the add-on name script.module.utils acceptable? I don't like it much, but it is a collection of some generally small helpers without much in common in between them. I checked leia and matrix branches and there is no collision.

I assume that I don't have to change internal module names, etc. to eliminate use of kodi or xbmc, although I plan on changing a few, where it seems to make sense.

2021-08-17 17:08 UTC, enen92 commented
Anything you like is fine. Please make sure it doesn't overlap with any existing module in pypi just to avoid confusion. Please note the module is not shown in the add-on browser/to users so the name and Id doesn't need to be anything pretty

2021-08-19 02:48 UTC, fbacher commented
I want to confirm something. In repo-scripts I upload the files that will go into the installable package (which is what I did). There is no importing or reference to my  git repo. My repo and repo-scripts are distinct and they are unaware of each other.
Correct?

2021-08-19 12:33 UTC, enen92 commented
Yeah that should be fine, this is a repository (or at least the source of the repo). You only need to make sure the src tag in add-on.xml mentions the upstream of your add-on (your git repo and project)

2021-08-24 10:47 UTC, enen92 requested changes
See comments. Thanks for the submission

2021-08-24 10:47 UTC, enen92 commented on script.module.kodi65/lib/kodi65/listitem.py
> +        if infos:
Note this is now deprecated and belongs to infotag

2021-08-24 10:47 UTC, enen92 commented on script.module.kodi65/lib/kodi65/player.py
> +        listitem.setInfo(type='video',
Deprecated

2021-08-24 10:47 UTC, enen92 commented on script.module.kodi65/lib/kodi65/player.py
> +        while not self.stopped:
Better check also abortRequested

2021-08-24 10:47 UTC, enen92 commented on script.module.kodi65/lib/kodi65/selectdialog.py
> +    xbmc.executebuiltin("Dialog.Close(busydialog)")
Avoid calling this in v19++, use dialogbusynocancel

2021-08-24 10:47 UTC, enen92 commented on script.module.kodi65/lib/kodi65/utils.py
> +                                thumbnailImage=vid.thumbnail,
Thumbnail args were removed, please use setart

2021-08-24 10:47 UTC, enen92 commented on script.module.kodi65/lib/kodi65/utils.py
> +    listitem.setInfo(type='video',
Deprecated

2021-08-24 10:47 UTC, enen92 commented on script.module.kodi65/lib/kodi65/utils.py
> +        headers = {'User-agent': 'Kodi/17.0 ( phil65@kodi.tv )'}
Email not valid anymore

2021-08-24 10:47 UTC, enen92 commented on script.module.kodi65/lib/kodi65/youtube.py
> +BASE_URL = "https://www.googleapis.com/youtube/v3/"
Do you have a new api key or are you reusing Phil's?

2021-09-07 15:40 UTC, closed without merging

2021-09-09 00:38 UTC, fbacher commented
Closed by accident, but since I started over on my branch, it was probably just as well. New request opened.