[script.module.kutils] 1.2.1+matrix.7
xbmc/repo-scripts pull request #2099
Opened 2021-09-07 20:46 UTC by fbacher

### Description
This is my second attempt, after making, I believe, all of the recommended changes from the first attempt. This time I figured out how to do the subtree merge so that changes are tracked to my repository. Unfortunately, this destroyed the tracking of the first pull request.

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

2021-09-09 00:23 UTC, fbacher commented
Added fix for a regression. Had to try several times to get down to one commit

2021-09-09 16:50 UTC, fbacher commented
Fixed file permissions identified by checker.

2021-09-12 13:00 UTC, enen92 requested changes
Minor. After that it's good to go

2021-09-12 14:58 UTC, fbacher commented on script.module.kutils/.gitignore
> +# Byte-compiled / optimized / DLL files
Ok. I'll commit change after resolving version change issue (see comment below)

2021-09-12 14:58 UTC, fbacher commented on script.module.kutils/lib/kutils/player.py
> +        while not monitor.waitForAbort(0.1):
Ok. I'll commit change after resolving version change issue (see comment below)

2021-09-12 14:58 UTC, fbacher commented
Would it cause grief if I change version to 1.3.0 at this late stage? It seems that changing the addon name as well as lib path, etc. would warrant more than a +matrix.7 suffix to the previous version. I should have thought about this earlier. 

I'm not sure what impact this would have on the PR, since it has the version embedded. I'm fine to leave the version as is to avoid complications.

2021-09-12 15:06 UTC, enen92 commented
That's fine. You don't need the matrix version identifier as this add-on will be only on the matrix branch. We use those identifiers to distinguish exact same versions in Leia and matrix.

2021-09-12 15:48 UTC, fbacher commented
Passed very basic tests

2021-09-12 15:48 UTC, enen92 approved these changes

2021-09-12 15:49 UTC, merged