[service.listenbrainz] 0.2.1
xbmc/repo-scripts pull request #2160
Opened 2021-11-28 17:30 UTC by Freso

### Description

Allows submitting listens to [ListenBrainz](https://listenbrainz.org/).

This is the final version for the Leia branch. Working on a [Python 3-only version](https://gitlab.com/Freso/service.listenbrainz/-/tree/matrix) for submitting for Matrix.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

2021-12-05 13:13 UTC, basrieter requested changes
Please review my changes.

2021-12-05 13:13 UTC, basrieter commented on service.listenbrainz/addon.xml
> +		<license>GNU GENERAL PUBLIC LICENSE Version 2</license>
Please use the license SPDX (See https://spdx.org/licenses/)

2021-12-05 13:13 UTC, basrieter commented on service.listenbrainz/listener.py
> +            xbmc.executebuiltin(
Better to use `xbmcgui.Dialog().notification()`

2021-12-05 13:13 UTC, basrieter commented on service.listenbrainz/listener.py
> +            xbmc.executebuiltin(
Better to use `xbmcgui.Dialog().notification()`

2021-12-05 13:13 UTC, basrieter commented on service.listenbrainz/utils.py
> +        xbmc.executebuiltin(
Better to use `xbmcgui.Dialog().notification()`

2021-12-05 13:13 UTC, basrieter commented on service.listenbrainz/utils.py
> +            xbmc.executebuiltin(
Better to use `xbmcgui.Dialog().notification()`

2021-12-05 13:13 UTC, basrieter commented on service.listenbrainz/utils.py
> +                xbmc.executebuiltin(
Better to use `xbmcgui.Dialog().notification()`

2021-12-05 13:13 UTC, basrieter commented on service.listenbrainz/listener.py
> +            xbmc.executebuiltin(
Better to use `xbmcgui.Dialog().notification()`

2021-12-05 13:13 UTC, basrieter commented on service.listenbrainz/utils.py
> +DATAPATH = xbmc.translatePath(
use `xbmcvfs.translatePath`, `xbmc.translatePath` is deprecated.

2021-12-06 16:09 UTC, Freso commented
Unless any of these changes are hard blockers, the proposed changes won’t be making it into the `leia` branch for this addon. I’ll update the code for the `matrix` version.

2021-12-06 20:12 UTC, basrieter commented
> Unless any of these changes are hard blockers, the proposed changes won’t be making it into the `leia` branch for this addon. I’ll update the code for the `matrix` version.

Would it not make sense to keep them in sync?

2021-12-07 09:29 UTC, Freso commented
It would, and if anyone volunteers to backport changes from `matrix` to `leia`, they’re welcome to do so. I have no interest in dealing with Python 2 any more than I absolutely have to. :)

2021-12-10 21:37 UTC, basrieter commented
> It would, and if anyone volunteers to backport changes from `matrix` to `leia`, they’re welcome to do so. I have no interest in dealing with Python 2 any more than I absolutely have to. :)

Ok, I understand. So out of curiosity: why the Leia version then?

2021-12-10 21:38 UTC, basrieter commented
BTW: Please do continue on the changes in the Matrix version, so I can merge it.

2021-12-14 17:30 UTC, Freso commented
> So out of curiosity: why the Leia version then?

Because development on this add-on started on Leia, so the code is already there.

2021-12-29 23:01 UTC, basrieter commented
We had an internal discussion on accepting new Python 2 add-ons in Leia. And in the light of us trying to get rid of Python 2 (which is end of life) and wanting user to move Kodi Matrix which runs Python 3, I will have to reject this PR. With Nexus on its way the era of Python 2 add-ons is almost over. 

I hope you understand our decision and will keeping supporting the Matrix version of your add-on.

2021-12-29 23:01 UTC, closed without merging