[service.listenbrainz] 0.3.0
xbmc/repo-scripts pull request #2161
Opened 2021-11-28 18:16 UTC by Freso

### Description

Enable submitting listens to [ListenBrainz](https://listenbrainz.org/).

See also https://github.com/xbmc/repo-scripts/pull/2160 for version for Leia.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

2021-12-05 13:23 UTC, basrieter requested changes
Please review my changes.

2021-12-05 13:23 UTC, basrieter commented on service.listenbrainz/addon.xml
> +		<license>GNU GENERAL PUBLIC LICENSE Version 2</license>
Please use the license SPDX (See https://spdx.org/licenses/)

2021-12-05 13:23 UTC, basrieter commented on service.listenbrainz/listener.py
> +            xbmc.executebuiltin(
Better to use `xbmcgui.Dialog().notification()`

2021-12-05 13:23 UTC, basrieter commented on service.listenbrainz/listener.py
> +            xbmc.executebuiltin(
Better to use `xbmcgui.Dialog().notification()`

2021-12-05 13:23 UTC, basrieter commented on service.listenbrainz/listener.py
> +            xbmc.executebuiltin(
Better to use `xbmcgui.Dialog().notification()`

2021-12-05 13:23 UTC, basrieter commented on service.listenbrainz/utils.py
> +        xbmc.executebuiltin(
Better to use `xbmcgui.Dialog().notification()`

2021-12-05 13:23 UTC, basrieter commented on service.listenbrainz/utils.py
> +            xbmc.executebuiltin(
Better to use `xbmcgui.Dialog().notification()`

2021-12-05 13:23 UTC, basrieter commented on service.listenbrainz/utils.py
> +                xbmc.executebuiltin(
Better to use `xbmcgui.Dialog().notification()`

2021-12-05 13:23 UTC, basrieter commented on service.listenbrainz/utils.py
> +DATAPATH = xbmc.translatePath(
use `xbmcvfs.translatePath`, `xbmc.translatePath` is deprecated.

2021-12-14 17:27 UTC, Freso commented
> Please review my changes.

These should all have been addressed in 0.3.1. :)

2021-12-14 21:09 UTC, basrieter approved these changes

2021-12-14 21:10 UTC, merged