[script.timers] 3.0.0
xbmc/repo-scripts pull request #2252
Opened 2022-04-13 12:12 UTC by Heckie75

### Description
- Support folders and playlists for scheduling, (feature request https://github.com/Heckie75/kodi-addon-timers/issues/7)
- Separated configuration of media and system actions, e.g. shutdown Kodi
- Enable resuming media that has been stopped after timer has finished
- Enable repating media and playlists
- Refactoring (rewrite of scheduler)

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

2022-04-13 21:18 UTC, basrieter requested changes
Please check my minor change?

2022-04-13 21:18 UTC, basrieter commented on script.timers/script.py
>          xbmc.executebuiltin("Addon.OpenSettings(%s)" %
Why not do `addon.openSettings()`?

2022-04-14 08:48 UTC, Heckie75 commented on script.timers/script.py
>          xbmc.executebuiltin("Addon.OpenSettings(%s)" %
I have changed all appearances from ```executebuiltin``` to ```addon.openSettings()```

2022-04-14 15:52 UTC, basrieter approved these changes

2022-04-14 15:52 UTC, merged