[service.subtitles.opensubtitles-com] 1.0.0
xbmc/repo-scripts pull request #2274
Opened 2022-05-12 12:22 UTC by opensubtitlesdev

### Description
This extension is the new official opensubtitles add-on, using the new REST API from opensubtitles.com.
The code is based on the previous extension, but will now evolve on its own, maintained by the main opensubtitles developers. Users are still able to use the previous extension, but are encouraged to upgrade.

Opensubtitles.com is the new opensubtitles website,  who will in term completely replace opensubtitles.org. It uses a totally new database, old accounts can be imported [here](https://www.opensubtitles.com/en/users/import) but will not work with this extension.

Register for a new account [here](https://www.opensubtitles.com/en/users/sign_up) if you are new to opensubtitles

### Checklist:

-  [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
-  [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
-  [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

2022-05-28 09:21 UTC, romanvm commented
Please remove compiled .mo language files. Kodi does not use gettext proper so those files are not needed.

2022-05-28 09:23 UTC, romanvm commented
Also please remove compiled python bytecode files along with `__pycache__` directories. Such files and directories (and .mo files as well) should not be commited to Git.

2022-05-28 16:51 UTC, romanvm commented
Please remove empty files as well.

2022-05-28 16:52 UTC, romanvm requested changes

2022-06-10 09:27 UTC, opensubtitlesdev commented on service.subtitles.opensubtitles-com/resources/lib/cache.py
> +# -*- coding: utf-8 -*-
ok, I removed the empty files, encoding comments, and compiled mo as suggested.

2022-06-10 09:32 UTC, opensubtitlesdev commented on service.subtitles.opensubtitles-com/resources/lib/data_collector.py
> +            "imdb_id": xbmc.getInfoLabel("VideoPlayer.IMDBNumber")}
Our API works better if querying sending the file name, and moviehash, so I removed all imdb id's and unique ID's reference.

2022-06-11 18:26 UTC, romanvm commented
Do you really need empty `.placeholder` file?

2022-06-12 06:58 UTC, jujudellago commented
probably not.... no idea why it was there, I removed it.

2022-06-12 09:34 UTC, romanvm approved these changes

2022-06-16 22:11 UTC, merged