[service.projcontrol] 1.4.0
xbmc/repo-scripts pull request #2335
Opened 2022-11-17 07:21 UTC by fredrik-eriksson

### Description
This is an updated version of the plugin previously included in [krypton](https://github.com/xbmc/repo-scripts/pull/868). Service add-on to Kodi for controling projectors with an optional RESTful API. This is intended to be used on stand-alone media centers running Kodi.

Project github page: https://github.com/fredrik-eriksson/kodi_projcontrol

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

2022-11-27 17:30 UTC, pkscout requested changes

2022-11-27 17:30 UTC, pkscout commented on service.projcontrol/resources/settings.xml
> +<?xml version="1.0" encoding="utf-8" standalone="yes"?>
Please convert the settings file to the new settings format.  The old settings format stills works, but for forward compatibility, we'd like everyone to start using the new format now.

https://kodi.wiki/view/Add-on_settings_conversion#Converting_addon_settings

One of the Team Kodi members wrote an addon that will convert other addon settings that will probably get you 95% of the way there (or might do it all).

https://gitlab.com/ronie/script.settings-convert

2022-12-04 08:36 UTC, fredrik-eriksson commented
settings.xml has been converted now. That convert-script sure was a lifesaver; thanks!

2026-03-15 12:34 UTC, pkscout approved these changes

2026-03-15 12:35 UTC, pkscout approved these changes

2026-03-15 19:54 UTC, merged