[plugin.script.omgtv] 1.0.0
xbmc/repo-scripts pull request #2341
Opened 2022-11-24 12:26 UTC by kabcasa

### Description
OMGTV!!! offers over 5,000 IPTV channels with electronic program guides including television, radio and CCTV.  This add on will enable Kodi to watch our free list of channels.  You can also watch your favorite channels.  Just create an account at OMGTV!!!, search our catalog and bookmark your favorites.  Then change the email address in this addon and watch your favorite channels on Kodi.  Its that easy!
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [ x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

2022-11-27 18:03 UTC, pkscout requested changes

2022-11-27 18:03 UTC, pkscout commented on plugin.script.omgtv/addon.xml
> +    <extension point="xbmc.python.pluginsource" library="addon.py">
There is a different repo for plugins.  This needs to be submitted there for review.

https://github.com/xbmc/repo-plugins

2022-11-27 18:03 UTC, pkscout commented
I'm going to leave this open for now, but this PR should be closed, as it needs to be submitted to the plugin repo, not the scripts repo.

2022-11-28 01:54 UTC, kabcasa commented
Ok i will load it to plugins repo.
Thank you.

2022-11-28 12:23 UTC, closed without merging