[service.subtitles.ktuvit] 4.0.0
xbmc/repo-scripts pull request #2442
Opened 2023-04-23 11:38 UTC by CaTzil

### Description

[Ktuvit](https://ktuvit.me/) subtitle plugin suitable for Nexus version
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

2023-05-20 21:13 UTC, romanvm requested changes
Please fix `addon.xml`, other changes are not mandatory.

2023-05-20 21:13 UTC, romanvm commented on service.subtitles.ktuvit/addon.xml
> +    <license>GNU GENERAL PUBLIC LICENSE. Version 2, June 1991</license>
Please use SPDX license identifier: https://spdx.org/licenses/

2023-05-20 21:13 UTC, romanvm commented on service.subtitles.ktuvit/resources/lib/SUBUtilities.py
> +# -*- coding: utf-8 -*-
No need for this in Python 3

2023-05-20 21:13 UTC, romanvm commented on service.subtitles.ktuvit/service.py
> +def get_params(string=""):
This this ugly as hell function can be replaced with `dict(parse_qsl(sys.argv[2][1:]))`

2023-10-31 18:27 UTC, CaTzil commented
I've made the addon changes, can you review it?

2024-01-01 21:21 UTC, romanvm commented
Please fix the license identifier and the addon will be ready to be merged. Other comments are not mandatory.

2024-01-02 08:37 UTC, CaTzil commented
@romanvm, I've updated my PR, please review it 🙏🏽

2024-04-08 06:54 UTC, CaTzil commented
Ping?

2024-07-07 08:22 UTC, romanvm approved these changes

2024-07-07 08:22 UTC, merged