[service.subtitles.opensubtitles-com] 1.0.4
xbmc/repo-scripts pull request #2579
Opened 2024-01-17 08:18 UTC by opensubtitlesdev

### Description

Multiple fixes on file path, language submitted by user "[pannal](https://github.com/pannal)" [opensubtitlesdev/service.subtitles.opensubtitles-com](https://github.com/opensubtitlesdev/service.subtitles.opensubtitles-com/pull/)
Improvements of the error messages for the user

### Checklist:

    * [x ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project.

    * [ x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document

    * [ x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :

    * Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.

    * [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.

    * Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API

    * [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.

    * This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.

    * Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

2024-01-20 01:10 UTC, opensubtitlesdev commented
spending so much time answering support tickets for bugs solved by this release... please merge it...

2024-01-21 20:43 UTC, romanvm requested changes

2024-01-21 20:43 UTC, romanvm commented on service.subtitles.opensubtitles-com/resources/lib/os/provider.py
> +            print(f"Username: {self.username}, Password: {self.password}")
Please use `xbmc.log()` instead

2024-01-21 20:43 UTC, romanvm commented
Please fix one minor issue

2024-01-22 02:23 UTC, opensubtitlesdev commented on service.subtitles.opensubtitles-com/resources/lib/os/provider.py
> +            print(f"Username: {self.username}, Password: {self.password}")
ok it's changed

2024-01-22 02:36 UTC, opensubtitlesdev commented
ok, fixed, added a last minute little change in the data collection that caused errors with streamed movies 
https://github.com/opensubtitlesdev/service.subtitles.opensubtitles-com/pull/20

2024-01-30 08:31 UTC, merged