[weather.ha] 0.0.5b
xbmc/repo-scripts pull request #2614
Opened 2024-04-21 12:05 UTC by Eugeniusz-Gienek

### Description

The plugin which is aimed to get the weather from the user's Home Assistant server.
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

2024-04-21 13:03 UTC, basrieter requested changes
Please see my comments.

2024-04-21 13:03 UTC, basrieter commented on weather.ha/lib/ha_weather.py
> +            sleep(RETRY_DELAY_S)
Please don't use `sleep` as it prevents Kodi from shutting down the script. Use the `MyMonitor.waitForAbort(10)` like the other weather add-ons do (https://github.com/xbmc/repo-scripts/blob/26fc0ca904c51d0078b8193c571356dd30b417a8/weather.multi/lib/weather.py#L104C37-L104C54)

2024-04-21 13:03 UTC, basrieter commented on weather.ha/lib/ha_weather.py
> +from time import sleep
Don't use sleep in the add-ons.

2024-04-21 13:03 UTC, basrieter commented on weather.ha/lib/ha_weather.py
> +            sleep(RETRY_DELAY_S)
Same here. Don't use `sleep()`

2024-04-21 13:08 UTC, Eugeniusz-Gienek commented on weather.ha/forecasts.example.yaml
Yes, in Home Assistant - in order for the plugin to work you have to put it in HA.

2024-04-21 15:29 UTC, Eugeniusz-Gienek reviewed
Fixed the "sleep" issue

2024-04-21 15:34 UTC, Eugeniusz-Gienek reviewed
Fix timing to match other weather plugins

2024-04-27 09:19 UTC, basrieter approved these changes

2024-04-27 09:19 UTC, merged